# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "user-login", "add-full-access-control", "fix-tests" ]
    # paths:
    #   - 'backend/**'
  pull_request:
    branches: [ "main" ]
    # paths:
    #   - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ATLAS_TEST_USERNAME: ${{ vars.ATLAS_TEST_USERNAME }}
      ATLAS_TEST_PASSWORD: ${{ vars.ATLAS_TEST_PASSWORD }}

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Print environment variables
      run: |
        echo ${{ env.ATLAS_TEST_USERNAME }}
        echo $ATLAS_TEST_USERNAME
        echo ${{ vars.ATLAS_TEST_USERNAME }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      env:
        ATLAS_TEST_USERNAME: ${{ vars.ATLAS_TEST_USERNAME }}
        ATLAS_TEST_PASSWORD: ${{ vars.ATLAS_TEST_PASSWORD }}
      with:
        cache-dependency-path: backend/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name : Test backend
      run: npm test
